name: Open Tabs
on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 10 minutes
jobs:
  open-tabs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests undetected-chromedriver
      - name: Install distutils
        run: sudo apt-get install python3-distutils -y
      - name: Download ChromeDriver
        run: |
          wget https://chromedriver.storage.googleapis.com/$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
      - name: Run script
        run: python open_tabs.py
