name: Open Tabs
on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute
jobs:
  open-tabs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify the Python version you need
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils
          sudo apt-get install -y libnss3 libgconf-2-4
      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
          google-chrome --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests undetected-chromedriver
      - name: Download ChromeDriver
        run: |
          wget https://chromedriver.storage.googleapis.com/$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
      - name: Run script with debugging
        run: |
          ps aux | grep chrome  # Check if Chrome is running
          netstat -tuln  # List network ports in use
          python open_tabs.py

